// Generated by Verd Compiler v0.1.0 — DO NOT EDIT
#![allow(unused_variables, unused_mut, dead_code, non_snake_case)]

#[derive(Clone, Debug)]
enum V {
    Num(f64),
    Txt(String),
    Bool(bool),
    Some(Box<V>),
    None,
    Void,
}

impl std::fmt::Display for V {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            V::Num(n) => if n.fract()==0.0 { write!(f,"{}",*n as i64) } else { write!(f,"{}",n) },
            V::Txt(s) => write!(f,"{}",s),
            V::Bool(b) => write!(f,"{}",b),
            V::Some(v) => write!(f,"some({})",v),
            V::None    => write!(f,"none"),
            V::Void    => Ok(()),
        }
    }
}

fn verd_add(l: V, r: V) -> V {
    match (&l, &r) {
        (V::Num(a), V::Num(b)) => V::Num(a + b),
        (V::Txt(a), V::Txt(b)) => V::Txt(format!("{}{}", a, b)),
        (V::Txt(a), _)         => V::Txt(format!("{}{}", a, r)),
        _                      => V::Void,
    }
}

fn verd_print(args: &[V]) {
    let s: Vec<String> = args.iter().map(|v| v.to_string()).collect();
    println!("{}", s.join(" "));
}

fn verd_truthy(v: &V) -> bool {
    match v { V::Bool(false)|V::None|V::Void => false, V::Num(n) if *n==0.0 => false, _ => true }
}

fn v_square(_args: &[V]) -> V {
    let v_n = _args.get(0).cloned().unwrap_or(V::Void);
    return { let _l = v_n.clone(); let _r = v_n.clone(); match (&_l, &_r) { (V::Num(a), V::Num(b)) => V::Num(a * b), _ => V::Void } };
    V::Void
}

fn v_power_sum(_args: &[V]) -> V {
    let v_x = _args.get(0).cloned().unwrap_or(V::Void);
    let v_y = _args.get(1).cloned().unwrap_or(V::Void);
    return verd_add(v_square(&[v_x.clone()]), v_square(&[v_y.clone()]));
    V::Void
}

fn v_double(_args: &[V]) -> V {
    let v_n = _args.get(0).cloned().unwrap_or(V::Void);
    return verd_add(v_n.clone(), v_n.clone());
    V::Void
}

fn v_add_ten(_args: &[V]) -> V {
    let v_n = _args.get(0).cloned().unwrap_or(V::Void);
    return verd_add(v_n.clone(), V::Num(10_f64));
    V::Void
}

fn v_find_user(_args: &[V]) -> V {
    let v_id = _args.get(0).cloned().unwrap_or(V::Void);
    return V::Some(Box::new(V::Txt("Huseyn".to_string())));
    V::Void
}

fn v_find_missing(_args: &[V]) -> V {
    let v_id = _args.get(0).cloned().unwrap_or(V::Void);
    return V::None;
    V::Void
}

fn v_safe_divide(_args: &[V]) -> V {
    let v_x = _args.get(0).cloned().unwrap_or(V::Void);
    let v_y = _args.get(1).cloned().unwrap_or(V::Void);
    return { let _l = v_x.clone(); let _r = v_y.clone(); match (&_l, &_r) { (V::Num(a), V::Num(b)) => V::Num(a / b), _ => V::Void } };
    V::Void
}

fn v_bad_divide(_args: &[V]) -> V {
    panic!("{}", V::Txt("ZeroDivision: cannot divide by zero".to_string()));
    V::Void
}

fn v_greet(_args: &[V]) -> V {
    let v_who = _args.get(0).cloned().unwrap_or(V::Void);
    return verd_add(verd_add(V::Txt("Hello, ".to_string()), v_who.clone()), V::Txt("!".to_string()));
    V::Void
}

fn main() {
    verd_print(&[V::Txt("=== 1. Variables ===".to_string())]);
    let v_language = V::Txt("Verd".to_string());
    let mut v_version = V::Num(1_f64);
    verd_print(&[V::Txt("Language:".to_string()), v_language.clone()]);
    verd_print(&[V::Txt("Version:".to_string()), v_version.clone()]);
    v_version = verd_add(v_version.clone(), V::Num(1_f64));
    verd_print(&[V::Txt("Updated version:".to_string()), v_version.clone()]);
    verd_print(&[V::Txt("".to_string())]);
    verd_print(&[V::Txt("=== 2. Arithmetic ===".to_string())]);
    let v_a = V::Num(20_f64);
    let v_b = V::Num(4_f64);
    verd_print(&[V::Txt("20 + 4 =".to_string()), verd_add(v_a.clone(), v_b.clone())]);
    verd_print(&[V::Txt("20 - 4 =".to_string()), { let _l = v_a.clone(); let _r = v_b.clone(); match (&_l, &_r) { (V::Num(a), V::Num(b)) => V::Num(a - b), _ => V::Void } }]);
    verd_print(&[V::Txt("20 * 4 =".to_string()), { let _l = v_a.clone(); let _r = v_b.clone(); match (&_l, &_r) { (V::Num(a), V::Num(b)) => V::Num(a * b), _ => V::Void } }]);
    verd_print(&[V::Txt("20 / 4 =".to_string()), { let _l = v_a.clone(); let _r = v_b.clone(); match (&_l, &_r) { (V::Num(a), V::Num(b)) => V::Num(a / b), _ => V::Void } }]);
    verd_print(&[V::Txt("20 % 6 =".to_string()), { let _l = V::Num(20_f64); let _r = V::Num(6_f64); match (&_l, &_r) { (V::Num(a), V::Num(b)) => V::Num((*a as i64 % *b as i64) as f64), _ => V::Void } }]);
    verd_print(&[V::Txt("".to_string())]);
    verd_print(&[V::Txt("=== 3. Op (Function) ===".to_string())]);
    verd_print(&[V::Txt("square(7) =".to_string()), v_square(&[V::Num(7_f64)])]);
    verd_print(&[V::Txt("power_sum(3, 4) =".to_string()), v_power_sum(&[V::Num(3_f64), V::Num(4_f64)])]);
    verd_print(&[V::Txt("".to_string())]);
    verd_print(&[V::Txt("=== 4. Cycle (Loop) ===".to_string())]);
    let mut v_i = V::Num(1_f64);
    let mut v_total = V::Num(0_f64);
    while { let _vt1 = { let _l = v_i.clone(); let _r = V::Num(6_f64); match (&_l, &_r) { (V::Num(a), V::Num(b)) => V::Bool(a < b), _ => V::Bool(false) } }; verd_truthy(&_vt1) } {
        v_total = verd_add(v_total.clone(), v_i.clone());
        v_i = verd_add(v_i.clone(), V::Num(1_f64));
    }
    verd_print(&[V::Txt("Sum of 1 to 5 =".to_string()), v_total.clone()]);
    verd_print(&[V::Txt("".to_string())]);
    verd_print(&[V::Txt("=== 5. Pipeline |> ===".to_string())]);
    let mut _vt2 = V::Num(5_f64);
    let _vt3 = v_double(&[_vt2]);
    let _vt4 = v_add_ten(&[_vt3]);
    verd_print(&[_vt4]);
    verd_print(&[V::Txt("".to_string())]);
    verd_print(&[V::Txt("=== 6. match / some / none ===".to_string())]);
    let _vt5 = v_find_user(&[V::Num(1_f64)]);
    match _vt5 {
        V::Some(_v_name) => {
            let v_name = *_v_name;
            verd_print(&[V::Txt("Found:".to_string()), v_name.clone()]);
        }
        V::None => {
            verd_print(&[V::Txt("Not found".to_string())]);
        }
        _ => {}
    }
    let _vt6 = v_find_missing(&[V::Num(99_f64)]);
    match _vt6 {
        V::Some(_v_name) => {
            let v_name = *_v_name;
            verd_print(&[V::Txt("Found:".to_string()), v_name.clone()]);
        }
        V::None => {
            verd_print(&[V::Txt("Not found".to_string())]);
        }
        _ => {}
    }
    verd_print(&[V::Txt("".to_string())]);
    verd_print(&[V::Txt("=== 7. rise / catch ===".to_string())]);
    verd_print(&[V::Txt("10 / 2 =".to_string()), v_safe_divide(&[V::Num(10_f64), V::Num(2_f64)])]);
    {
        let _catch_result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            v_bad_divide(&[]);
        }));
        if let Err(_panic_val) = _catch_result {
            let _rise_str = _panic_val.downcast_ref::<String>().map(|s| s.as_str()).unwrap_or("unknown error").to_string();
            let v_err = V::Txt(_rise_str);
            verd_print(&[V::Txt("Caught error:".to_string()), v_err.clone()]);
        }
    }
    verd_print(&[V::Txt("".to_string())]);
    verd_print(&[V::Txt("=== 8. String operations ===".to_string())]);
    let mut _vt7 = V::Txt("Verd".to_string());
    let _vt8 = v_greet(&[_vt7]);
    verd_print(&[_vt8]);
    let mut _vt9 = V::Txt("World".to_string());
    let _vt10 = v_greet(&[_vt9]);
    verd_print(&[_vt10]);
    verd_print(&[V::Txt("".to_string())]);
    verd_print(&[V::Txt("All tests passed!".to_string())]);
}
