/* Generated by Verd Compiler — DO NOT EDIT */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>

typedef enum { VERD_NUMBER, VERD_TEXT, VERD_BOOL, VERD_SOME, VERD_NONE, VERD_VOID } VerdTag;

typedef struct VerdValue VerdValue;
struct VerdValue {
    VerdTag tag;
    union {
        double   number;
        char*    text;
        int      boolean;
        VerdValue* some_inner;
    };
};

static VerdValue verd_num(double n)      { VerdValue v; v.tag = VERD_NUMBER; v.number = n; return v; }
static VerdValue verd_text(const char* s){ VerdValue v; v.tag = VERD_TEXT; v.text = strdup(s); return v; }
static VerdValue verd_bool(int b)        { VerdValue v; v.tag = VERD_BOOL; v.boolean = b; return v; }
static VerdValue verd_some(VerdValue inner){ VerdValue v; v.tag = VERD_SOME; v.some_inner = malloc(sizeof(VerdValue)); *v.some_inner = inner; return v; }
static VerdValue verd_none_val()         { VerdValue v; v.tag = VERD_NONE; return v; }
static VerdValue verd_void_val()         { VerdValue v; v.tag = VERD_VOID; return v; }

static void verd_print(VerdValue v) {
    switch(v.tag) {
        case VERD_NUMBER: if(v.number == (long long)v.number) printf("%lld", (long long)v.number); else printf("%g", v.number); break;
        case VERD_TEXT:   printf("%s", v.text); break;
        case VERD_BOOL:   printf("%s", v.boolean ? "true" : "false"); break;
        case VERD_SOME:   printf("some("); verd_print(*v.some_inner); printf(")"); break;
        case VERD_NONE:   printf("none"); break;
        default: break;
    }
}

static VerdValue verd_concat(VerdValue a, VerdValue b) {
    char buf[4096]; snprintf(buf, sizeof(buf), "%s%s",
        a.tag == VERD_TEXT ? a.text : "",
        b.tag == VERD_TEXT ? b.text : "");
    return verd_text(buf);
}

static jmp_buf _verd_jump_buf;
static char    _verd_rise_msg[512];

VerdValue verd_square(VerdValue* _args, int _argc);
VerdValue verd_power_sum(VerdValue* _args, int _argc);
VerdValue verd_double(VerdValue* _args, int _argc);
VerdValue verd_add_ten(VerdValue* _args, int _argc);
VerdValue verd_find_user(VerdValue* _args, int _argc);
VerdValue verd_find_missing(VerdValue* _args, int _argc);
VerdValue verd_safe_divide(VerdValue* _args, int _argc);
VerdValue verd_bad_divide(VerdValue* _args, int _argc);
VerdValue verd_greet(VerdValue* _args, int _argc);

int main(void) {
    (verd_print(verd_text("=== 1. Variables ===")), printf("\n"), verd_void_val());
    VerdValue verd_language = verd_text("Verd");
    VerdValue verd_version = verd_num(1);
    (verd_print(verd_text("Language:")), verd_print(verd_language), printf("\n"), verd_void_val());
    (verd_print(verd_text("Version:")), verd_print(verd_version), printf("\n"), verd_void_val());
    verd_version = ((verd_version).tag == VERD_TEXT ? verd_concat(verd_version, verd_num(1)) : verd_num((verd_version).number + (verd_num(1)).number));
    (verd_print(verd_text("Updated version:")), verd_print(verd_version), printf("\n"), verd_void_val());
    (verd_print(verd_text("")), printf("\n"), verd_void_val());
    (verd_print(verd_text("=== 2. Arithmetic ===")), printf("\n"), verd_void_val());
    VerdValue verd_a = verd_num(20);
    VerdValue verd_b = verd_num(4);
    (verd_print(verd_text("20 + 4 =")), verd_print(((verd_a).tag == VERD_TEXT ? verd_concat(verd_a, verd_b) : verd_num((verd_a).number + (verd_b).number))), printf("\n"), verd_void_val());
    (verd_print(verd_text("20 - 4 =")), verd_print(verd_num((verd_a).number - (verd_b).number)), printf("\n"), verd_void_val());
    (verd_print(verd_text("20 * 4 =")), verd_print(verd_num((verd_a).number * (verd_b).number)), printf("\n"), verd_void_val());
    (verd_print(verd_text("20 / 4 =")), verd_print(verd_num((verd_a).number / (verd_b).number)), printf("\n"), verd_void_val());
    (verd_print(verd_text("20 % 6 =")), verd_print(verd_num((long long)(verd_num(20)).number % (long long)(verd_num(6)).number)), printf("\n"), verd_void_val());
    (verd_print(verd_text("")), printf("\n"), verd_void_val());
    (verd_print(verd_text("=== 3. Op (Function) ===")), printf("\n"), verd_void_val());
    (verd_print(verd_text("square(7) =")), verd_print(verd_square((VerdValue[]){ verd_num(7) }, 1)), printf("\n"), verd_void_val());
    (verd_print(verd_text("power_sum(3, 4) =")), verd_print(verd_power_sum((VerdValue[]){ verd_num(3), verd_num(4) }, 2)), printf("\n"), verd_void_val());
    (verd_print(verd_text("")), printf("\n"), verd_void_val());
    (verd_print(verd_text("=== 4. Cycle (Loop) ===")), printf("\n"), verd_void_val());
    VerdValue verd_i = verd_num(1);
    VerdValue verd_total = verd_num(0);
    while (((verd_bool((verd_i).number < (verd_num(6)).number)).tag == VERD_BOOL ? (verd_bool((verd_i).number < (verd_num(6)).number)).boolean : (verd_bool((verd_i).number < (verd_num(6)).number)).tag == VERD_NUMBER ? (verd_bool((verd_i).number < (verd_num(6)).number)).number != 0 : 0)) {
        verd_total = ((verd_total).tag == VERD_TEXT ? verd_concat(verd_total, verd_i) : verd_num((verd_total).number + (verd_i).number));
        verd_i = ((verd_i).tag == VERD_TEXT ? verd_concat(verd_i, verd_num(1)) : verd_num((verd_i).number + (verd_num(1)).number));
    }
    (verd_print(verd_text("Sum of 1 to 5 =")), verd_print(verd_total), printf("\n"), verd_void_val());
    (verd_print(verd_text("")), printf("\n"), verd_void_val());
    (verd_print(verd_text("=== 5. Pipeline |> ===")), printf("\n"), verd_void_val());
    VerdValue _vt1 = verd_num(5);
    VerdValue _vt2 = verd_double((VerdValue[]){ _vt1 }, 1);
    VerdValue _vt3 = verd_add_ten((VerdValue[]){ _vt2 }, 1);
    verd_print(_vt3); printf("\n");
    (verd_print(verd_text("")), printf("\n"), verd_void_val());
    (verd_print(verd_text("=== 6. match / some / none ===")), printf("\n"), verd_void_val());
    VerdValue _vt4 = verd_find_user((VerdValue[]){ verd_num(1) }, 1);
    if (_vt4.tag == VERD_SOME) {
        VerdValue verd_name = *_vt4.some_inner;
        (verd_print(verd_text("Found:")), verd_print(verd_name), printf("\n"), verd_void_val());
    } else {
        (verd_print(verd_text("Not found")), printf("\n"), verd_void_val());
    }
    VerdValue _vt5 = verd_find_missing((VerdValue[]){ verd_num(99) }, 1);
    if (_vt5.tag == VERD_SOME) {
        VerdValue verd_name = *_vt5.some_inner;
        (verd_print(verd_text("Found:")), verd_print(verd_name), printf("\n"), verd_void_val());
    } else {
        (verd_print(verd_text("Not found")), printf("\n"), verd_void_val());
    }
    (verd_print(verd_text("")), printf("\n"), verd_void_val());
    (verd_print(verd_text("=== 7. rise / catch ===")), printf("\n"), verd_void_val());
    (verd_print(verd_text("10 / 2 =")), verd_print(verd_safe_divide((VerdValue[]){ verd_num(10), verd_num(2) }, 2)), printf("\n"), verd_void_val());
    if (setjmp(_verd_jump_buf) == 0) {
        verd_bad_divide(NULL, 0);
    } else {
        VerdValue verd_err = verd_text(_verd_rise_msg);
        (verd_print(verd_text("Caught error:")), verd_print(verd_err), printf("\n"), verd_void_val());
    }
    (verd_print(verd_text("")), printf("\n"), verd_void_val());
    (verd_print(verd_text("=== 8. String operations ===")), printf("\n"), verd_void_val());
    VerdValue _vt6 = verd_text("Verd");
    VerdValue _vt7 = verd_greet((VerdValue[]){ _vt6 }, 1);
    verd_print(_vt7); printf("\n");
    VerdValue _vt8 = verd_text("World");
    VerdValue _vt9 = verd_greet((VerdValue[]){ _vt8 }, 1);
    verd_print(_vt9); printf("\n");
    (verd_print(verd_text("")), printf("\n"), verd_void_val());
    (verd_print(verd_text("All tests passed!")), printf("\n"), verd_void_val());
    return 0;
}

VerdValue verd_square(VerdValue* _args, int _argc) {
    VerdValue verd_n = _argc > 0 ? _args[0] : verd_void_val();
    return verd_num((verd_n).number * (verd_n).number);
    return verd_void_val();
}

VerdValue verd_power_sum(VerdValue* _args, int _argc) {
    VerdValue verd_x = _argc > 0 ? _args[0] : verd_void_val();
    VerdValue verd_y = _argc > 1 ? _args[1] : verd_void_val();
    return ((verd_square((VerdValue[]){ verd_x }, 1)).tag == VERD_TEXT ? verd_concat(verd_square((VerdValue[]){ verd_x }, 1), verd_square((VerdValue[]){ verd_y }, 1)) : verd_num((verd_square((VerdValue[]){ verd_x }, 1)).number + (verd_square((VerdValue[]){ verd_y }, 1)).number));
    return verd_void_val();
}

VerdValue verd_double(VerdValue* _args, int _argc) {
    VerdValue verd_n = _argc > 0 ? _args[0] : verd_void_val();
    return ((verd_n).tag == VERD_TEXT ? verd_concat(verd_n, verd_n) : verd_num((verd_n).number + (verd_n).number));
    return verd_void_val();
}

VerdValue verd_add_ten(VerdValue* _args, int _argc) {
    VerdValue verd_n = _argc > 0 ? _args[0] : verd_void_val();
    return ((verd_n).tag == VERD_TEXT ? verd_concat(verd_n, verd_num(10)) : verd_num((verd_n).number + (verd_num(10)).number));
    return verd_void_val();
}

VerdValue verd_find_user(VerdValue* _args, int _argc) {
    VerdValue verd_id = _argc > 0 ? _args[0] : verd_void_val();
    return verd_some(verd_text("Huseyn"));
    return verd_void_val();
}

VerdValue verd_find_missing(VerdValue* _args, int _argc) {
    VerdValue verd_id = _argc > 0 ? _args[0] : verd_void_val();
    return verd_none_val();
    return verd_void_val();
}

VerdValue verd_safe_divide(VerdValue* _args, int _argc) {
    VerdValue verd_x = _argc > 0 ? _args[0] : verd_void_val();
    VerdValue verd_y = _argc > 1 ? _args[1] : verd_void_val();
    return verd_num((verd_x).number / (verd_y).number);
    return verd_void_val();
}

VerdValue verd_bad_divide(VerdValue* _args, int _argc) {
    VerdValue _vt10 = verd_text("ZeroDivision: cannot divide by zero");
    if (_vt10.tag == VERD_TEXT) strncpy(_verd_rise_msg, _vt10.text, 511);
    longjmp(_verd_jump_buf, 1);
    return verd_void_val();
}

VerdValue verd_greet(VerdValue* _args, int _argc) {
    VerdValue verd_who = _argc > 0 ? _args[0] : verd_void_val();
    return ((((verd_text("Hello, ")).tag == VERD_TEXT ? verd_concat(verd_text("Hello, "), verd_who) : verd_num((verd_text("Hello, ")).number + (verd_who).number))).tag == VERD_TEXT ? verd_concat(((verd_text("Hello, ")).tag == VERD_TEXT ? verd_concat(verd_text("Hello, "), verd_who) : verd_num((verd_text("Hello, ")).number + (verd_who).number)), verd_text("!")) : verd_num((((verd_text("Hello, ")).tag == VERD_TEXT ? verd_concat(verd_text("Hello, "), verd_who) : verd_num((verd_text("Hello, ")).number + (verd_who).number))).number + (verd_text("!")).number));
    return verd_void_val();
}

