use crate::ast::{BinOp, Expr};

/// Takes a Verd AST and produces a complete, compilable C source file.
pub struct CGenerator {
    output: String,
    indent: usize,
    temp_counter: usize,
    func_names: Vec<String>,  // declared op names for forward declarations
}

impl CGenerator {
    pub fn new() -> Self {
        CGenerator {
            output: String::new(),
            indent: 0,
            temp_counter: 0,
            func_names: Vec::new(),
        }
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    fn emit(&mut self, s: &str) {
        let indent = "    ".repeat(self.indent);
        self.output.push_str(&indent);
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn emit_raw(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn fresh_temp(&mut self) -> String {
        self.temp_counter += 1;
        format!("_vt{}", self.temp_counter)
    }

    fn mangle(name: &str) -> String {
        format!("verd_{}", name)
    }

    // ── Public entry point ───────────────────────────────────────────────────

    /// Generate a full C source file from the given AST program.
    pub fn generate(&mut self, program: &[Expr]) -> String {
        self.collect_ops(program);
        self.emit_prelude();
        self.emit_forward_decls();
        self.emit_main_start();

        for expr in program {
            if matches!(expr, Expr::OpDecl { .. }) {
                // op declarations go OUTSIDE main — handled separately
                continue;
            }
            self.gen_stmt(expr);
        }

        self.emit_main_end();

        // Now emit all op definitions after main
        for expr in program {
            if let Expr::OpDecl { .. } = expr {
                self.gen_op_def(expr);
            }
        }

        self.output.clone()
    }

    // ── Collect op names for forward declarations ────────────────────────────

    fn collect_ops(&mut self, program: &[Expr]) {
        for expr in program {
            if let Expr::OpDecl { name, .. } = expr {
                self.func_names.push(name.clone());
            }
        }
    }

    // ── C Prelude ────────────────────────────────────────────────────────────

    fn emit_prelude(&mut self) {
        self.emit_raw("/* Generated by Verd Compiler — DO NOT EDIT */\n");
        self.emit_raw("#include <stdio.h>\n");
        self.emit_raw("#include <stdlib.h>\n");
        self.emit_raw("#include <string.h>\n");
        self.emit_raw("#include <setjmp.h>\n\n");

        // VerdValue — Verd's universal runtime value type
        self.emit_raw("typedef enum { VERD_NUMBER, VERD_TEXT, VERD_BOOL, VERD_SOME, VERD_NONE, VERD_VOID } VerdTag;\n\n");
        self.emit_raw("typedef struct VerdValue VerdValue;\n");
        self.emit_raw("struct VerdValue {\n");
        self.emit_raw("    VerdTag tag;\n");
        self.emit_raw("    union {\n");
        self.emit_raw("        double   number;\n");
        self.emit_raw("        char*    text;\n");
        self.emit_raw("        int      boolean;\n");
        self.emit_raw("        VerdValue* some_inner;\n");
        self.emit_raw("    };\n");
        self.emit_raw("};\n\n");

        // Constructors
        self.emit_raw("static VerdValue verd_num(double n)      { VerdValue v; v.tag = VERD_NUMBER; v.number = n; return v; }\n");
        self.emit_raw("static VerdValue verd_text(const char* s){ VerdValue v; v.tag = VERD_TEXT; v.text = strdup(s); return v; }\n");
        self.emit_raw("static VerdValue verd_bool(int b)        { VerdValue v; v.tag = VERD_BOOL; v.boolean = b; return v; }\n");
        self.emit_raw("static VerdValue verd_some(VerdValue inner){ VerdValue v; v.tag = VERD_SOME; v.some_inner = malloc(sizeof(VerdValue)); *v.some_inner = inner; return v; }\n");
        self.emit_raw("static VerdValue verd_none_val()         { VerdValue v; v.tag = VERD_NONE; return v; }\n");
        self.emit_raw("static VerdValue verd_void_val()         { VerdValue v; v.tag = VERD_VOID; return v; }\n\n");

        // print built-in
        self.emit_raw("static void verd_print(VerdValue v) {\n");
        self.emit_raw("    switch(v.tag) {\n");
        self.emit_raw("        case VERD_NUMBER: if(v.number == (long long)v.number) printf(\"%lld\", (long long)v.number); else printf(\"%g\", v.number); break;\n");
        self.emit_raw("        case VERD_TEXT:   printf(\"%s\", v.text); break;\n");
        self.emit_raw("        case VERD_BOOL:   printf(\"%s\", v.boolean ? \"true\" : \"false\"); break;\n");
        self.emit_raw("        case VERD_SOME:   printf(\"some(\"); verd_print(*v.some_inner); printf(\")\"); break;\n");
        self.emit_raw("        case VERD_NONE:   printf(\"none\"); break;\n");
        self.emit_raw("        default: break;\n");
        self.emit_raw("    }\n");
        self.emit_raw("}\n\n");

        // concat built-in
        self.emit_raw("static VerdValue verd_concat(VerdValue a, VerdValue b) {\n");
        self.emit_raw("    char buf[4096]; snprintf(buf, sizeof(buf), \"%s%s\",\n");
        self.emit_raw("        a.tag == VERD_TEXT ? a.text : \"\",\n");
        self.emit_raw("        b.tag == VERD_TEXT ? b.text : \"\");\n");
        self.emit_raw("    return verd_text(buf);\n");
        self.emit_raw("}\n\n");

        // rise/catch support
        self.emit_raw("static jmp_buf _verd_jump_buf;\n");
        self.emit_raw("static char    _verd_rise_msg[512];\n\n");
    }

    fn emit_forward_decls(&mut self) {
        for name in &self.func_names.clone() {
            self.emit_raw(&format!("VerdValue {}(VerdValue* _args, int _argc);\n", Self::mangle(name)));
        }
        self.emit_raw("\n");
    }

    fn emit_main_start(&mut self) {
        self.emit_raw("int main(void) {\n");
        self.indent = 1;
    }

    fn emit_main_end(&mut self) {
        self.indent = 1;
        self.emit("return 0;");
        self.emit_raw("}\n\n");
        self.indent = 0;
    }

    // ── Statement generation ─────────────────────────────────────────────────

    fn gen_stmt(&mut self, expr: &Expr) {
        match expr {
            Expr::Pin { name, value } => {
                let val = self.gen_expr(value);
                self.emit(&format!("VerdValue {} = {};", Self::mangle(name), val));
            }

            Expr::Flux { name, value } => {
                let val = self.gen_expr(value);
                self.emit(&format!("VerdValue {} = {};", Self::mangle(name), val));
            }

            Expr::Assign { name, value } => {
                let val = self.gen_expr(value);
                self.emit(&format!("{} = {};", Self::mangle(name), val));
            }

            Expr::Call { name, args } => {
                let call = self.gen_call(name, args);
                self.emit(&format!("{};", call));
            }

            Expr::Cycle { condition, body } => {
                let cond = self.gen_condition(condition);
                self.emit(&format!("while ({}) {{", cond));
                self.indent += 1;
                for s in body { self.gen_stmt(s); }
                self.indent -= 1;
                self.emit("}");
            }

            Expr::Match { subject, some_branch, none_branch } => {
                let subj = self.gen_expr(subject);
                let tmp = self.fresh_temp();
                self.emit(&format!("VerdValue {} = {};", tmp, subj));
                self.emit(&format!("if ({}.tag == VERD_SOME) {{", tmp));
                self.indent += 1;
                if let Some((bound, body)) = some_branch {
                    self.emit(&format!("VerdValue {} = *{}.some_inner;", Self::mangle(bound), tmp));
                    for s in body { self.gen_stmt(s); }
                }
                self.indent -= 1;
                self.emit("} else {");
                self.indent += 1;
                if let Some(body) = none_branch {
                    for s in body { self.gen_stmt(s); }
                }
                self.indent -= 1;
                self.emit("}");
            }

            Expr::Catch { body, err_var, handler } => {
                self.emit("if (setjmp(_verd_jump_buf) == 0) {");
                self.indent += 1;
                for s in body { self.gen_stmt(s); }
                self.indent -= 1;
                self.emit("} else {");
                self.indent += 1;
                self.emit(&format!("VerdValue {} = verd_text(_verd_rise_msg);", Self::mangle(err_var)));
                for s in handler { self.gen_stmt(s); }
                self.indent -= 1;
                self.emit("}");
            }

            Expr::Rise(msg) => {
                let m = self.gen_expr(msg);
                let tmp = self.fresh_temp();
                self.emit(&format!("VerdValue {} = {};", tmp, m));
                self.emit(&format!("if ({}.tag == VERD_TEXT) strncpy(_verd_rise_msg, {}.text, 511);", tmp, tmp));
                self.emit("longjmp(_verd_jump_buf, 1);");
            }

            Expr::Pipeline { stages } => {
                // a |> b |> c  →  c(b(a))
                self.gen_pipeline_stmt(stages);
            }

            Expr::Question { condition, body } => {
                let cond = self.gen_condition(condition);
                self.emit(&format!("if ({}) {{", cond));
                self.indent += 1;
                for s in body { self.gen_stmt(s); }
                self.indent -= 1;
                self.emit("}");
            }

            // Op declarations are handled separately
            Expr::OpDecl { .. } => {}

            Expr::Yield(v) => {
                let val = self.gen_expr(v);
                self.emit(&format!("return {};", val));
            }

            _ => {
                let e = self.gen_expr(expr);
                self.emit(&format!("{};", e));
            }
        }
    }

    fn gen_pipeline_stmt(&mut self, stages: &[Expr]) {
        if stages.is_empty() { return; }

        // Build up: start with first value, pipe through each stage
        let first = self.gen_expr(&stages[0]);
        let tmp0 = self.fresh_temp();
        self.emit(&format!("VerdValue {} = {};", tmp0, first));
        let mut prev_tmp = tmp0;

        for stage in &stages[1..] {
            let stage_name = match stage {
                Expr::Identifier(n) => n.clone(),
                Expr::Call { name, .. } => name.clone(),
                _ => continue,
            };

            if stage_name == "print" {
                self.emit(&format!("verd_print({}); printf(\"\\n\");", prev_tmp));
                continue;
            }

            let next_tmp = self.fresh_temp();
            let args_c = format!("(VerdValue[]){{ {} }}", prev_tmp);
            self.emit(&format!("VerdValue {} = {}({}, 1);", next_tmp, Self::mangle(&stage_name), args_c));
            prev_tmp = next_tmp;
        }
    }

    // ── Op definition ────────────────────────────────────────────────────────

    fn gen_op_def(&mut self, expr: &Expr) {
        if let Expr::OpDecl { name, params, body, .. } = expr {
            self.emit_raw(&format!(
                "VerdValue {}(VerdValue* _args, int _argc) {{\n",
                Self::mangle(name)
            ));
            self.indent = 1;

            // Bind parameters from _args array
            for (i, param) in params.iter().enumerate() {
                self.emit(&format!(
                    "VerdValue {} = _argc > {} ? _args[{}] : verd_void_val();",
                    Self::mangle(param), i, i
                ));
            }

            for s in body { self.gen_stmt(s); }

            self.emit("return verd_void_val();");
            self.indent = 0;
            self.emit_raw("}\n\n");
        }
    }

    // ── Expression generation ────────────────────────────────────────────────

    fn gen_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Number(n) => format!("verd_num({})", n),
            Expr::Text(s)   => format!("verd_text(\"{}\")", s.replace('"', "\\\"").replace('\n', "\\n")),
            Expr::Bool(b)   => format!("verd_bool({})", if *b { 1 } else { 0 }),
            Expr::None      => "verd_none_val()".to_string(),

            Expr::Identifier(name) => Self::mangle(name),

            Expr::BinaryOp { op, left, right } => {
                self.gen_binop(op, left, right)
            }

            Expr::Call { name, args } => {
                self.gen_call(name, args)
            }

            _ => "verd_void_val()".to_string(),
        }
    }

    fn gen_call(&mut self, name: &str, args: &[Expr]) -> String {
        // Built-in: print
        if name == "print" {
            let parts: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
            // We'll emit statements for print — return empty
            // But since gen_call is used inline, we generate a compound expression
            // We use a helper approach: build the print as a statement chain
            let mut result = String::from("(");
            for (i, part) in parts.iter().enumerate() {
                if i > 0 { result.push_str(", "); }
                result.push_str(&format!("verd_print({})", part));
            }
            result.push_str(", printf(\"\\n\"), verd_void_val())");
            return result;
        }

        // Built-in: some(x)
        if name == "some" && args.len() == 1 {
            let inner = self.gen_expr(&args[0]);
            return format!("verd_some({})", inner);
        }

        // User-defined op
        let arg_exprs: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
        if arg_exprs.is_empty() {
            format!("{}(NULL, 0)", Self::mangle(name))
        } else {
            format!(
                "{}((VerdValue[]){{ {} }}, {})",
                Self::mangle(name),
                arg_exprs.join(", "),
                arg_exprs.len()
            )
        }
    }

    fn gen_pipeline_expr(&mut self, stages: &[Expr]) -> String {
        if stages.is_empty() { return "verd_void_val()".to_string(); }

        let mut current = self.gen_expr(&stages[0]);

        for stage in &stages[1..] {
            let stage_name = match stage {
                Expr::Identifier(n) => n.clone(),
                Expr::Call { name, .. } => name.clone(),
                _ => continue,
            };

            if stage_name == "print" {
                current = format!("(verd_print({}), printf(\"\\n\"), verd_void_val())", current);
                continue;
            }

            current = format!(
                "{}((VerdValue[]){{ {} }}, 1)",
                Self::mangle(&stage_name),
                current
            );
        }

        current
    }

    fn gen_binop(&mut self, op: &BinOp, left: &Expr, right: &Expr) -> String {
        let l = self.gen_expr(left);
        let r = self.gen_expr(right);

        let c_op = match op {
            BinOp::Add  => {
                // Could be string concat or number add
                return format!(
                    "(({l}).tag == VERD_TEXT ? verd_concat({l}, {r}) : verd_num(({l}).number + ({r}).number))",
                    l = l, r = r
                );
            }
            BinOp::Sub  => return format!("verd_num(({}).number - ({}).number)", l, r),
            BinOp::Mul  => return format!("verd_num(({}).number * ({}).number)", l, r),
            BinOp::Div  => return format!("verd_num(({}).number / ({}).number)", l, r),
            BinOp::Mod  => return format!("verd_num((long long)({}).number % (long long)({}).number)", l, r),
            BinOp::Eq   => return format!("verd_bool(({l}).tag == ({r}).tag && ({l}).tag == VERD_NUMBER && ({l}).number == ({r}).number)", l=l, r=r),
            BinOp::NotEq=> return format!("verd_bool(!(({l}).tag == ({r}).tag && ({l}).number == ({r}).number))", l=l, r=r),
            BinOp::Lt   => return format!("verd_bool(({}).number < ({}).number)", l, r),
            BinOp::Gt   => return format!("verd_bool(({}).number > ({}).number)", l, r),
            BinOp::LtEq => return format!("verd_bool(({}).number <= ({}).number)", l, r),
            BinOp::GtEq => return format!("verd_bool(({}).number >= ({}).number)", l, r),
        };
        unreachable!()
    }

    fn gen_condition(&mut self, expr: &Expr) -> String {
        let e = self.gen_expr(expr);
        format!("(({e}).tag == VERD_BOOL ? ({e}).boolean : ({e}).tag == VERD_NUMBER ? ({e}).number != 0 : 0)", e=e)
    }
}
