use crate::ast::{BinOp, Expr};

/// Takes a Verd AST and produces a complete, compilable Rust source file.
/// This gives us Rust-speed performance without needing GCC.
pub struct RustGenerator {
    output: String,
    indent: usize,
    temp_counter: usize,
    op_names: Vec<String>,
}

impl RustGenerator {
    pub fn new() -> Self {
        RustGenerator {
            output: String::new(),
            indent: 0,
            temp_counter: 0,
            op_names: Vec::new(),
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    fn emit(&mut self, s: &str) {
        let indent = "    ".repeat(self.indent);
        self.output.push_str(&indent);
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn emit_raw(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn fresh_temp(&mut self) -> String {
        self.temp_counter += 1;
        format!("_vt{}", self.temp_counter)
    }

    fn mangle(name: &str) -> String {
        // avoid clashing with Rust keywords
        match name {
            "type" | "match" | "use" | "mod" | "fn" | "let" | "mut" |
            "return" | "loop" | "while" | "for" | "if" | "else" | "pub" => {
                format!("v_{}", name)
            }
            _ => format!("v_{}", name),
        }
    }

    // ── Public entry point ───────────────────────────────────────────────────

    pub fn generate(&mut self, program: &[Expr]) -> String {
        self.collect_ops(program);
        self.emit_prelude();

        // Emit op (function) definitions first
        for expr in program {
            if let Expr::OpDecl { .. } = expr {
                self.gen_op_def(expr);
            }
        }

        // Emit main()
        self.emit_raw("fn main() {\n");
        self.indent = 1;

        for expr in program {
            if matches!(expr, Expr::OpDecl { .. }) { continue; }
            self.gen_stmt(expr);
        }

        self.indent = 0;
        self.emit_raw("}\n");

        self.output.clone()
    }

    fn collect_ops(&mut self, program: &[Expr]) {
        for expr in program {
            if let Expr::OpDecl { name, .. } = expr {
                self.op_names.push(name.clone());
            }
        }
    }

    // ── Prelude (VerdValue type + helpers) ────────────────────────────────────

    fn emit_prelude(&mut self) {
        self.emit_raw("// Generated by Verd Compiler v0.1.0 — DO NOT EDIT\n");
        self.emit_raw("#![allow(unused_variables, unused_mut, dead_code, non_snake_case)]\n\n");

        // The universal Verd runtime value
        self.emit_raw("#[derive(Clone, Debug)]\n");
        self.emit_raw("enum V {\n");
        self.emit_raw("    Num(f64),\n");
        self.emit_raw("    Txt(String),\n");
        self.emit_raw("    Bool(bool),\n");
        self.emit_raw("    Some(Box<V>),\n");
        self.emit_raw("    None,\n");
        self.emit_raw("    Void,\n");
        self.emit_raw("}\n\n");

        // Display
        self.emit_raw("impl std::fmt::Display for V {\n");
        self.emit_raw("    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {\n");
        self.emit_raw("        match self {\n");
        self.emit_raw("            V::Num(n) => if n.fract()==0.0 { write!(f,\"{}\",*n as i64) } else { write!(f,\"{}\",n) },\n");
        self.emit_raw("            V::Txt(s) => write!(f,\"{}\",s),\n");
        self.emit_raw("            V::Bool(b) => write!(f,\"{}\",b),\n");
        self.emit_raw("            V::Some(v) => write!(f,\"some({})\",v),\n");
        self.emit_raw("            V::None    => write!(f,\"none\"),\n");
        self.emit_raw("            V::Void    => Ok(()),\n");
        self.emit_raw("        }\n");
        self.emit_raw("    }\n");
        self.emit_raw("}\n\n");

        // verd_add: smart +
        self.emit_raw("fn verd_add(l: V, r: V) -> V {\n");
        self.emit_raw("    match (&l, &r) {\n");
        self.emit_raw("        (V::Num(a), V::Num(b)) => V::Num(a + b),\n");
        self.emit_raw("        (V::Txt(a), V::Txt(b)) => V::Txt(format!(\"{}{}\", a, b)),\n");
        self.emit_raw("        (V::Txt(a), _)         => V::Txt(format!(\"{}{}\", a, r)),\n");
        self.emit_raw("        _                      => V::Void,\n");
        self.emit_raw("    }\n");
        self.emit_raw("}\n\n");

        // verd_print: variadic via Vec
        self.emit_raw("fn verd_print(args: &[V]) {\n");
        self.emit_raw("    let s: Vec<String> = args.iter().map(|v| v.to_string()).collect();\n");
        self.emit_raw("    println!(\"{}\", s.join(\" \"));\n");
        self.emit_raw("}\n\n");

        // is_truthy
        self.emit_raw("fn verd_truthy(v: &V) -> bool {\n");
        self.emit_raw("    match v { V::Bool(false)|V::None|V::Void => false, V::Num(n) if *n==0.0 => false, _ => true }\n");
        self.emit_raw("}\n\n");
    }

    // ── Statement generation ─────────────────────────────────────────────────

    fn gen_stmt(&mut self, expr: &Expr) {
        match expr {
            Expr::Pin { name, value } => {
                let v = self.gen_expr(value);
                self.emit(&format!("let {} = {};", Self::mangle(name), v));
            }
            Expr::Flux { name, value } => {
                let v = self.gen_expr(value);
                self.emit(&format!("let mut {} = {};", Self::mangle(name), v));
            }
            Expr::Assign { name, value } => {
                let v = self.gen_expr(value);
                self.emit(&format!("{} = {};", Self::mangle(name), v));
            }
            Expr::Call { name, args } => {
                let c = self.gen_call(name, args);
                self.emit(&format!("{};", c));
            }
            Expr::Yield(v) => {
                let e = self.gen_expr(v);
                self.emit(&format!("return {};", e));
            }
            Expr::Rise(msg) => {
                let m = self.gen_expr(msg);
                self.emit(&format!("panic!(\"{{}}\", {});", m));
            }
            Expr::Cycle { condition, body } => {
                let cond = self.gen_expr(condition);
                let tmp = self.fresh_temp();
                self.emit(&format!("while {{ let {} = {}; verd_truthy(&{}) }} {{", tmp, cond, tmp));
                self.indent += 1;
                for s in body { self.gen_stmt(s); }
                self.indent -= 1;
                self.emit("}");
            }
            Expr::Match { subject, some_branch, none_branch } => {
                let subj = self.gen_expr(subject);
                let tmp = self.fresh_temp();
                self.emit(&format!("let {} = {};", tmp, subj));
                self.emit(&format!("match {} {{", tmp));
                self.indent += 1;
                if let Some((bound, body)) = some_branch {
                    self.emit(&format!("V::Some(_{}) => {{", Self::mangle(bound)));
                    self.indent += 1;
                    self.emit(&format!("let {} = *_{};", Self::mangle(bound), Self::mangle(bound)));
                    for s in body { self.gen_stmt(s); }
                    self.indent -= 1;
                    self.emit("}");
                }
                if let Some(body) = none_branch {
                    self.emit("V::None => {");
                    self.indent += 1;
                    for s in body { self.gen_stmt(s); }
                    self.indent -= 1;
                    self.emit("}");
                }
                self.emit("_ => {}");
                self.indent -= 1;
                self.emit("}");
            }
            Expr::Catch { body, err_var, handler } => {
                // Use std::panic::catch_unwind — rise generates panic!()
                self.emit("{");
                self.indent += 1;
                self.emit("let _catch_result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {");
                self.indent += 1;
                for s in body { self.gen_stmt(s); }
                self.indent -= 1;
                self.emit("}));");
                self.emit("if let Err(_panic_val) = _catch_result {");
                self.indent += 1;
                self.emit("let _rise_str = _panic_val.downcast_ref::<String>().map(|s| s.as_str()).unwrap_or(\"unknown error\").to_string();");
                self.emit(&format!("let {} = V::Txt(_rise_str);", Self::mangle(err_var)));
                for s in handler { self.gen_stmt(s); }
                self.indent -= 1;
                self.emit("}");
                self.indent -= 1;
                self.emit("}");
            }
            Expr::Question { condition, body } => {
                let cond = self.gen_expr(condition);
                let tmp = self.fresh_temp();
                self.emit(&format!("if {{ let {} = {}; verd_truthy(&{}) }} {{", tmp, cond, tmp));
                self.indent += 1;
                for s in body { self.gen_stmt(s); }
                self.indent -= 1;
                self.emit("}");
            }
            Expr::Pipeline { stages } => {
                self.gen_pipeline_stmt(stages);
            }
            Expr::OpDecl { .. } => {} // handled separately
            _ => {
                let e = self.gen_expr(expr);
                self.emit(&format!("{};", e));
            }
        }
    }

    fn gen_pipeline_stmt(&mut self, stages: &[Expr]) {
        if stages.is_empty() { return; }
        let first = self.gen_expr(&stages[0]);
        let tmp0 = self.fresh_temp();
        self.emit(&format!("let mut {} = {};", tmp0, first));
        let mut prev = tmp0;

        for stage in &stages[1..] {
            let name = match stage {
                Expr::Identifier(n) | Expr::Call { name: n, .. } => n.clone(),
                _ => continue,
            };
            if name == "print" {
                self.emit(&format!("verd_print(&[{}]);", prev));
                continue;
            }
            let next = self.fresh_temp();
            self.emit(&format!("let {} = {}(&[{}]);", next, Self::mangle(&name), prev));
            prev = next;
        }
    }

    // ── Op definition ─────────────────────────────────────────────────────────

    fn gen_op_def(&mut self, expr: &Expr) {
        if let Expr::OpDecl { name, params, body, .. } = expr {
            // Use Result<V, String> so rise works inside ops
            self.emit_raw(&format!(
                "fn {}(_args: &[V]) -> V {{\n",
                Self::mangle(name)
            ));
            self.indent = 1;

            for (i, param) in params.iter().enumerate() {
                self.emit(&format!(
                    "let {} = _args.get({}).cloned().unwrap_or(V::Void);",
                    Self::mangle(param), i
                ));
            }

            for s in body { self.gen_stmt(s); }

            self.emit("V::Void");
            self.indent = 0;
            self.emit_raw("}\n\n");
        }
    }

    // ── Expression generation ─────────────────────────────────────────────────

    fn gen_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Number(n) => format!("V::Num({}_f64)", n),
            Expr::Text(s)   => format!("V::Txt(\"{}\".to_string())", s.replace('"', "\\\"").replace('\n', "\\n")),
            Expr::Bool(b)   => format!("V::Bool({})", b),
            Expr::None      => "V::None".to_string(),
            Expr::Identifier(n) => format!("{}.clone()", Self::mangle(n)),

            Expr::BinaryOp { op, left, right } => {
                self.gen_binop(op, left, right)
            }
            Expr::Call { name, args } => self.gen_call(name, args),

            Expr::Pipeline { stages } => {
                self.gen_pipeline_expr(stages)
            }

            _ => "V::Void".to_string(),
        }
    }

    fn gen_call(&mut self, name: &str, args: &[Expr]) -> String {
        if name == "print" {
            let parts: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
            return format!("verd_print(&[{}])", parts.join(", "));
        }
        if name == "some" && args.len() == 1 {
            let inner = self.gen_expr(&args[0]);
            return format!("V::Some(Box::new({}))", inner);
        }

        let arg_exprs: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
        format!("{}(&[{}])", Self::mangle(name), arg_exprs.join(", "))
    }

    fn gen_pipeline_expr(&mut self, stages: &[Expr]) -> String {
        if stages.is_empty() { return "V::Void".to_string(); }
        let mut current = self.gen_expr(&stages[0]);
        for stage in &stages[1..] {
            let name = match stage {
                Expr::Identifier(n) | Expr::Call { name: n, .. } => n.clone(),
                _ => continue,
            };
            if name == "print" {
                current = format!("{{ verd_print(&[{}]); V::Void }}", current);
                continue;
            }
            current = format!("{}(&[{}])", Self::mangle(&name), current);
        }
        current
    }

    fn gen_binop(&mut self, op: &BinOp, left: &Expr, right: &Expr) -> String {
        let l = self.gen_expr(left);
        let r = self.gen_expr(right);
        // We use a block-expression: { let _l = ...; let _r = ...; match (&_l, &_r) { ... } }
        // This avoids move errors since we match on references.
        let block = |pat: &str, body: &str| -> String {
            format!(
                "{{ let _l = {l}; let _r = {r}; match (&_l, &_r) {{ {pat} => {body}, _ => V::Void }} }}",
                l=l, r=r, pat=pat, body=body
            )
        };
        let cmp = |pat: &str, body: &str| -> String {
            format!(
                "{{ let _l = {l}; let _r = {r}; match (&_l, &_r) {{ {pat} => {body}, _ => V::Bool(false) }} }}",
                l=l, r=r, pat=pat, body=body
            )
        };
        match op {
            BinOp::Add  => format!("verd_add({}, {})", l, r),
            BinOp::Sub  => block("(V::Num(a), V::Num(b))", "V::Num(a - b)"),
            BinOp::Mul  => block("(V::Num(a), V::Num(b))", "V::Num(a * b)"),
            BinOp::Div  => block("(V::Num(a), V::Num(b))", "V::Num(a / b)"),
            BinOp::Mod  => block("(V::Num(a), V::Num(b))", "V::Num((*a as i64 % *b as i64) as f64)"),
            BinOp::Eq   => format!(
                "{{ let _l = {l}; let _r = {r}; match (&_l, &_r) {{ (V::Num(a),V::Num(b)) => V::Bool(a==b), (V::Txt(a),V::Txt(b)) => V::Bool(a==b), (V::Bool(a),V::Bool(b)) => V::Bool(a==b), _ => V::Bool(false) }} }}",
                l=l, r=r
            ),
            BinOp::NotEq=> format!(
                "{{ let _l = {l}; let _r = {r}; match (&_l, &_r) {{ (V::Num(a),V::Num(b)) => V::Bool(a!=b), (V::Txt(a),V::Txt(b)) => V::Bool(a!=b), _ => V::Bool(true) }} }}",
                l=l, r=r
            ),
            BinOp::Lt   => cmp("(V::Num(a), V::Num(b))", "V::Bool(a < b)"),
            BinOp::Gt   => cmp("(V::Num(a), V::Num(b))", "V::Bool(a > b)"),
            BinOp::LtEq => cmp("(V::Num(a), V::Num(b))", "V::Bool(a <= b)"),
            BinOp::GtEq => cmp("(V::Num(a), V::Num(b))", "V::Bool(a >= b)"),
        }
    }
}
